### PR TITLE
Set up GitHub Actions

### PR DESCRIPTION
**Pull request by elbeejay**
Set up some GitHub actions starting with a simple continuous integration workflow to try installing the `GOSTnets` package on the 3 major operating systems (Linux, Windows, MacOS) for Python 3.8 and then running `Python -c import GOSTnets` as a very basic test of the package having installed and existing.

Right now we are limited to Python 3.8 because of the hard-pinned dependency `rtree-0.9.3` per the project's readme.

### CODE REVIEW

**Review by g4brielvs — CHANGES_REQUESTED** [review]
@elbeejay Thank you for opening this PR. While this testing workflow can go in parallel, I'd recommend migrating to `pyproject.toml` first (https://github.com/worldbank/GOSTnets/issues/40 and https://github.com/worldbank/GOSTnets/issues/41), including the dependencies and optional dependencies. For example, in the new setup, the dependencies can be added and pinned and the 
 the installation could be simplified to `pip install gostnets` or `pip install "gostnets[optimization]"` (or even include all dependencies by default because they are not large). Then this PR can be updated and merged. What are your thoughts?

Additionally, the documentation, tests and release workflow (e.g., [BlackMarblePy](https://github.com/worldbank/blackmarblepy)) can also be prioritized. If you agree with the course of action, could you please create and prioritize these as [tasks](https://github.com/orgs/worldbank/projects/19)?

**Comment by elbeejay** [comment]
> @elbeejay Thank you for opening this PR. While this testing workflow can go in parallel, I'd recommend migrating to `pyproject.toml` first (#40 and #41), including the dependencies and optional dependencies. For example, in the new setup, the dependencies can be added and pinned and the installation could be simplified to `pip install gostnets` or `pip install "gostnets[optimization]"` (or even include all dependencies by default because they are not large). Then this PR can be updated and merged. What are your thoughts?

Sure, I'd just started here because the PEP stuff wasn't clear to me ([from here](https://github.com/orgs/worldbank/discussions/5#discussioncomment-8186347)) but now that we've cleared that up I can set up the `pyproject.toml`.

**Comment by g4brielvs** [comment]
@elbeejay #40 is now closed.

**Comment by elbeejay** [comment]
Added a "publish" workflow for automatic publishing to pypi. May requre configuration on the pypi side per [this document](https://docs.pypi.org/trusted-publishers/adding-a-publisher/)

**Comment by g4brielvs** [comment]
> Added a "publish" workflow for automatic publishing to pypi. May requre configuration on the pypi side per [this document](https://docs.pypi.org/trusted-publishers/adding-a-publisher/)

@elbeejay Thanks! FYI I have requested a `worldbank` organization on PyPI, but I'll do it (just like Blamable) in the meantime.

**Pull request merged**
